services:
  mongo:
    image: mongo:7
    container_name: mongo-rs0
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27018:27017" # host:container (we use host 27018 to avoid conflict)
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-init-replica:
    image: mongo:7
    depends_on:
      - mongo
    entrypoint: >
      bash -lc "
      for i in {1..60}; do
        mongosh --host mongo:27017 --quiet --eval 'db.runCommand({ ping: 1 })' && break || sleep 2;
      done;
      mongosh --host mongo:27017 --quiet <<'EOF'
      try {
        rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongo:27017' }] })
      } catch (e) {}
      EOF
      "
    restart: "no"

  mongo-express:
    image: mongo-express:1.0.2
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  mongo_data:
